import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const root = fileURLToPath(new URL('..', import.meta.url));
const read = (path) => readFileSync(`${root}/${path}`, 'utf8');

const info = read('appinfo/info.xml');
const routes = read('appinfo/routes.php');
const pageController = read('lib/Controller/PageController.php');
const selfServiceController = read('lib/Controller/SelfServiceController.php');
const template = read('templates/index.php');
const style = read('css/style.css');
const script = read('js/main.js');
const reportView = read('js/report-view.js');
const adminTemplate = read('templates/admin.php');
const adminScript = read('js/admin.js');
const adminAccessScript = read('js/admin-access.js');
const executionProfileScript = read('js/retention-execution-profile.js');
const riskScopeAuthorizationScript = read('js/risk-scope-authorization.js');

if (!info.includes('<id>flz_data_protection</id>')) throw new Error('Eindeutige FLZ-App-ID fehlt.');
if (!info.includes('<namespace>FlzDataProtection</namespace>')) throw new Error('FLZ-App-Namespace fehlt.');
if (info.includes('<app>')) throw new Error('Die Standalone-App besitzt eine fremde Laufzeitabhängigkeit.');
if (!info.includes('<route>flz_data_protection.page.index</route>')) throw new Error('Standalone-Navigation fehlt.');
if (!routes.includes("'name' => 'page#index'")) throw new Error('App-Route fehlt.');
if (!routes.includes("'name' => 'self_service#report'")) throw new Error('Self-Service-API-Route fehlt.');
if (!routes.includes("'url' => '/api/v1/self-service-report'")) throw new Error('Self-Service-API besitzt keinen stabilen Pfad.');
if (!routes.includes("'url' => '/api/v1/retention-review'")) throw new Error('Geschützte REVIEW-API fehlt.');
if (!pageController.includes('#[NoAdminRequired]')) throw new Error('Angemeldete Nicht-Admins erhalten keinen Self-Service-Einstieg.');
if (pageController.includes('PublicPage')) throw new Error('Der Self-Service-Einstieg wurde anonym freigegeben.');
if (!selfServiceController.includes('#[NoAdminRequired]')) throw new Error('Angemeldete Nicht-Admins erhalten keine Self-Service-Auskunft.');
if (selfServiceController.includes('PublicPage')) throw new Error('Die Self-Service-Auskunft wurde anonym freigegeben.');
if (!/function report\(\): JSONResponse/.test(selfServiceController)) throw new Error('Die Self-Service-API akzeptiert eine frei übermittelte Zielperson.');
if (!template.includes('id="data-protection-app"')) throw new Error('Semantischer App-Root fehlt.');
if (!template.includes('id="data-protection-retention"')) throw new Error('Operativer REVIEW-Bereich fehlt.');
if (!info.includes('<admin>OCA\\FlzDataProtection\\Settings\\Admin</admin>')) throw new Error('Datenschutz-Administration fehlt.');
if (!adminTemplate.includes('kein automatisches fachliches Leserecht')) throw new Error('Deny-by-default-Hinweis für native Admins fehlt.');
if (adminTemplate.includes('id="data-protection-full-access-form"')) throw new Error('Freigabesteuerung ist noch an die technische Administration gebunden.');
if (!template.includes("$_['canManageAdminAccess']")) throw new Error('DPO-geschützte Freigabesteuerung fehlt.');
if (!template.includes("$_['showMissingAdminGrant']")) throw new Error('Sichere Eintrittsmeldung für Admins ohne Freigabe fehlt.');
if (!template.includes("$_['showAdminAccessLink']")) throw new Error('Rollenabhängiger Direktlink fehlt.');
for (const contract of ['data-protection-admin-grant-warning', '<details', 'Datenschutzbeauftragte', 'target="_blank"']) if (!template.includes(contract)) throw new Error(`Titelwarnung für fehlenden Admin-Vollzugriff fehlt: ${contract}`);
if (!style.includes('.data-protection-admin-grant-warning')) throw new Error('Titelwarnung für fehlenden Admin-Vollzugriff ist nicht als kleines Floating-Icon gestaltet.');
if (!template.includes('id="data-protection-full-access-form"')) throw new Error('App-lokale Adminfreigabe fehlt.');
if (!template.includes('value="1440"')) throw new Error('Die maximale Dauer von 24 Stunden fehlt.');
if (adminTemplate.includes('name="allow_nextcloud_admin_review"')) throw new Error('Der alte unbefristete Adminzugriff ist noch konfigurierbar.');
if (!routes.includes("'url' => '/api/v1/admin/full-access'")) throw new Error('Adminfreigabe-API fehlt.');
if (!adminAccessScript.includes('data-protection-full-access-history')) throw new Error('Freigabehistorie wird nicht dargestellt.');
if (!adminAccessScript.includes('requesttoken = OC.requestToken')) throw new Error('Freigabemutationen senden kein CSRF-Token.');
for (const contract of ['data-protection-retention-execution-profile-form', 'performanceMonitoringProhibited', 'configurationValid']) {
    if (!template.includes(contract) && !executionProfileScript.includes(contract)) throw new Error(`Kundenprofil-UI-Vertrag fehlt: ${contract}`);
}
if (!template.includes('Noch nicht eingerichtet')) throw new Error('Der serverseitige Hinweis auf die optionale DPO-Dokumentation fehlt.');
if (!template.includes('appseitig unveränderliche Profilrevision')) throw new Error('Die append-only Wirkung der Profilrevision wird im Formular nicht transparent benannt.');
const profileSectionStart = template.indexOf("<?php if ($_['canConfigureRetentionExecutionProfile'] ?? false): ?>");
const setupNotice = template.indexOf('data-protection-retention-execution-profile-setup-required');
const firstProfileSectionEnd = template.indexOf('<?php endif; ?>', profileSectionStart);
if (profileSectionStart < 0 || setupNotice < profileSectionStart || setupNotice > firstProfileSectionEnd) throw new Error('Der Ersteinrichtungshinweis ist nicht auf DPO-Konfigurierende begrenzt.');
if (!executionProfileScript.includes('/api/v1/retention-execution-profile')) throw new Error('Die Kundenprofil-Konfiguration verwendet nicht den geschlossenen API-Pfad.');
if (!executionProfileScript.includes('requesttoken: OC.requestToken')) throw new Error('Die Kundenprofil-Mutation sendet kein CSRF-Token.');
if (/\/(execute|delete|run)\b|method\s*:\s*['"]DELETE['"]/i.test(executionProfileScript)) throw new Error('Die Kundenprofil-UI darf keinen Retention-Ausführungspfad enthalten.');
const executionActivationScript = read('js/retention-execution-activation.js');
if (!template.includes("$_['canConfigureRetentionExecutionActivation']")) throw new Error('Die technische Retention-Aktivierung ist nicht serverseitig auf Operatoren begrenzt.');
if (!executionActivationScript.includes('/api/v2/retention-execution-activation')) throw new Error('Die technische Aktivierung verwendet nicht den getrennten V2-Pfad.');
if (!executionActivationScript.includes('requesttoken: OC.requestToken')) throw new Error('Die technische Aktivierung sendet kein CSRF-Token.');
if (/(legalEvidence|authorizationReference|dpoConfirmed|agreement)/.test(executionActivationScript)) throw new Error('Rechts-/DPO-Evidenz ist weiterhin Eingabe der technischen Aktivierung.');
if (!template.includes("$_['canConfigureRiskScopeAuthorizations']")) throw new Error('Die Risikoscope-Konfiguration ist nicht serverseitig auf DPOs begrenzt.');
if (!template.includes('data-protection-risk-scope-authorization-form')) throw new Error('Das DPO-Formular für Risikoscopes fehlt.');
if (!template.includes('value="flzroom.secretariat_foreign_booking_intervention"')) throw new Error('Das DPO-Formular verwendet nicht die kanonische FLZ-Raumplaner-Scope-ID.');
if (!riskScopeAuthorizationScript.includes('/api/v1/risk-scope-authorizations')) throw new Error('Die Risikoscope-UI verwendet nicht den geschlossenen API-Pfad.');
if (!riskScopeAuthorizationScript.includes('requesttoken: OC.requestToken')) throw new Error('Die Risikoscope-Mutation sendet kein CSRF-Token.');
if (!adminScript.includes('requesttoken: OC.requestToken')) throw new Error('Einstellungsspeicherung sendet kein CSRF-Token.');
if (!reportView.includes('Noch sind keine Datenschutzprovider registriert.')) throw new Error('Fehlende Provider werden nicht transparent ausgewiesen.');
if (!script.includes('/api/v1/self-service-report')) throw new Error('Self-Service-Bericht wird nicht geladen.');
if (!script.includes("setAttribute('role', 'alert')")) throw new Error('Ladefehler besitzt keine zugängliche Fehlermeldung.');
if (!/\#data-protection-app\s*\{[^}]*height:\s*100%[^}]*min-height:\s*0[^}]*overflow-y:\s*auto/s.test(style)) throw new Error('Scrollvertrag fehlt.');
if (!script.includes("dataset.ready = 'true'")) throw new Error('App-Initialisierung fehlt.');

console.log('Filzmann Data Protection JavaScript/app contract passed.');

await import('./js/self-service-request-smoke.mjs');
await import('./js/self-service-report-smoke.mjs');
await import('./js/retention-review-smoke.mjs');
await import('./js/retention-execution-profile-smoke.mjs');
await import('./js/retention-execution-activation-smoke.mjs');
await import('./js/risk-scope-authorization-smoke.mjs');
await import('./js/compact-report-layout-smoke.mjs');
